### PR TITLE
Create universal bootstrap script

### PR DESCRIPTION
**Pull request by ghost**
Create a universal bootstrap script, that can be used to install Hypatia with Python2 on various platforms. Not ready for primetime yet, but here's a todo:
- [x] Python 3 support
- [x] Special case support
  - [ ] Linux Mint w/ Py3
  - [x] Arch Linux w/ Py3
  - [x] TravisCI support

### CODE REVIEW

**Comment by lillian-lemmer** [comment]
Feel free to merge once you're willing to also update documentation on the usage of this script. :)

**Comment by alxcenz** [comment]
:thumbsup: will do c:

**Comment by lillian-lemmer** [comment]
Thanks sweetie pie.

**Comment by alxcenz** [comment]
For me to implement the Linux Mint support, could I get someone with a Mint install handy to give me the contents of `/etc/os-release`? Cheers~

**Comment by SanketDG** [comment]
@alxcenz

```
NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.2 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

**Comment by lillian-lemmer** [comment]
Thank you so much, @SanketDG~

@alxcenz Thank you so much for all your awesome work! So you got Python 3 + Pygame working in the new Travis setup?

**Comment by alxcenz** [comment]
Travis Py3 builds appear to be passing but i can't check as I'm on my phone. Will fix remaining bugs and test Mint support in the morning. 

-----Original Message-----

**Comment by alxcenz** [comment]
The script is pretty much done now, ready for merge. @ejmr can I grab a second opinion before I merge?

**Comment by ejmr** [comment]
> @ejmr can I grab a second opinion before I merge?

Overall I think it looks good :smile: 

My linter complains about a few lines of code, namely `out` often being unused (and thus could be removed), and `found` serving no purpose in `guess_package_manager()`.  But that's stylistic stuff and doesn't actually affect the logic.

As far as functionality and behavior, I don't see any obvious problems or errors.  I can only test it on Ubuntu, but I ran into no issues.

**Comment by alxcenz** [comment]
Will fix those stylistic things and then merge. Cheers :)

**Comment by lillian-lemmer** [comment]
Thanks @ejmr, @alxcenz!

**Pull request merged**
