### PR TITLE
Image API Standardization, Generic Pygame Datatypes

### PR DESCRIPTION
**Pull request by lillian-lemmer**
The goal of the `finalize-image-api` branch is to both standardize the api of all image types, but also to fully conform all basic game image datatypes, e.g., animated sprite, etc.

This currently doesn't work, I just ask you follow my changes as I go along.

### CODE REVIEW

**Comment by lillian-lemmer** [comment]
I will also be moving all of `game.py` to be demo code.

**Comment by lillian-lemmer** [comment]
Scenes and tilemaps do not need to be separate. Let's get rid of the native file type for tilemaps, only use tiled editor's. support the default map format, don't require csv. move over the tmx map stuff to tiledmap editor.

**Comment by txanatan** [comment]
> Let's get rid of the native file type for tilemaps [...]

Why?

**Comment by lillian-lemmer** [comment]
Bitrot. It's totally superfluous (for now) because we're focusing entirely
on core features (common pieces to build the game, not the glue). The
architecture hadn't been thought through, it was a
spur-of-the-moment-implementation. I don't see us doing anything that Tiled
map editor wouldn't support in the foreseeable future. It is likely to
become unmaintained as the default for debugging and demo'ing is a TMX,
especially as the Tiled Map Editor actually makes our engine accessible to
all kinds of people. :)

**Comment by lillian-lemmer** [comment]
I'm very specifically talking about the map format we save in.

**Comment by txanatan** [comment]
But if we end up implementing our own editor (which I'd like to see, but I don't know what your plans are) then we'd need to reimplement our own map format anyway. The existing format isn't that great but it does have it's advantages (being easy to explain to beginners, being simple and thus easy to maintain). I'm not really all that bothered either way, and I do agree with you that Tiled is easy for new people to pick up and use with the engine.

**Comment by lillian-lemmer** [comment]
https://github.com/lillian-lemmer/sappho

**Pull request closed without merging**
